videojs.addLanguage("ko", {
    "Audio Player": "오디오 플레이어",
    "Video Player": "비디오 플레이어",
    "Play": "재생",
    "Pause": "일시정지",
    "Replay": "Replay",
    "Current Time": "현재 시간",
    "Duration": "지정 기간",
    "Remaining Time": "남은 시간",
    "Stream Type": "스트리밍 유형",
    "LIVE": "라이브",
    "Loaded": "로드됨",
    "Progress": "진행",
    "Progress Bar": "진행 표시 줄",
    "progress bar timing: 현재 시간={1} 지정 기간={2}": "{1} of {2}",
    "Fullscreen": "전체 화면",
    "Non-Fullscreen": "전체 화면 해제",
    "Mute": "음소거",
    "Unmute": "음소거 해제",
    "Playback Rate": "배속",
    "Subtitles": "자막 끄기",
    "subtitles off": "자막 끄기",
    "Captions": "자막",
    "captions off": "자막 끄기",
    "Captions Language": "자막언어",
    "captions toggle": "자막",
    "Chapters": "챕터",
    "Descriptions": "설명",
    "descriptions off": "설명 꺼짐",
    "Audio Track": "오디오 트랙",
    "Volume Level": "볼륨 레벨",
    "Bookmark": "북마크",
    "QNA": "QNA",
    "Index": "인덱스",
    "Setting": "설정",
    "Quality": "재생화질",
    "Hotkeys": "단축키",
    "Info": "플레이어 정보",
    "You aborted the media playback": "비디오 재생을 취소했습니다.",
    "A network error caused the media download to fail part-way.": "네트워크 오류로 인하여 비디오 일부를 다운로드하지 못 했습니다.",
    "The media could not be loaded, either because the server or network failed or because the format is not supported.": "비디오를 로드할 수 없습니다. 서버 혹은 네트워크 오류 때문이거나 지원되지 않는 형식 때문일 수 있습니다.",
    "The media playback was aborted due to a corruption problem or because the media used features your browser did not support.": "비디오 재생이 취소됐습니다. 비디오가 손상되었거나 비디오가 사용하는 기능을 브라우저에서 지원하지 않는 것 같습니다.",
    "No compatible source was found for this media.": "비디오에 호환되지 않는 소스가 있습니다.",
    "The media is encrypted and we do not have the keys to decrypt it.": "미디어가 암호화되어 있고 해독 할 수있는 키가 없습니다.",
    "Play Video": "동영상 재생",
    "Close": "닫기",
    "Close Modal Dialog": "모달 대화 상자 닫기",
    "Modal Window": "모달 창",
    "This is a modal window": "이것은 모달 윈도우입니다.",
    "This modal can be closed by pressing the Escape key or activating the close button.": "이 모달은 Esc 키를 누르거나 닫기 버튼을 활성화하여 닫을 수 있습니다.",
    ", opens captions settings dialog": ", 자막 설정 대화 상자를 엽니다.",
    ", opens subtitles settings dialog": ", 자막 설정 대화 상자를 엽니다.",
    ", opens descriptions settings dialog": ", 설명 설정 대화 상자를 엽니다.",
    ", selected": ", 선택됨",
    "captions settings": "자막 설정",
    "subtitles settings": "자막 설정",
    "descriptions settings": "설명 설정",
    "Text": "텍스트",
    "White": "White",
    "Black": "Black",
    "Red": "Red",
    "Green": "Green",
    "Blue": "Blue",
    "Yellow": "Yellow",
    "Magenta": "Magenta",
    "Cyan": "Cyan",
    "Background": "텍스트 배경",
    "Window": "영역",
    "Transparent": "투명",
    "Semi-Transparent": "반투명",
    "Opaque": "불투명",
    "Font Size": "글자 크기",
    "Text Edge Style": "텍스트 가장자리 스타일",
    "None": "없음",
    "Raised": "Raised",
    "Depressed": "Depressed",
    "Uniform": "Uniform",
    "Dropshadow": "Dropshadow",
    "Font Family": "글꼴",
    "Proportional Sans-Serif": "Proportional Sans-Serif",
    "Monospace Sans-Serif": "Monospace Sans-Serif",
    "Proportional Serif": "Proportional Serif",
    "Monospace Serif": "Monospace Serif",
    "Casual": "Casual",
    "Script": "Script",
    "Small Caps": "Small Caps",
    "Reset": "재설정",
    "restore all settings to the default values": "모든 설정을 기본값으로 복원",
    "Done": "완료",
    "Caption Settings Dialog": "자막 설정 대화 상자",
    "Beginning of dialog window. Escape will cancel and close the window.": "대화 상자 창 시작. 이스케이프시에 취소되고 창을 닫습니다.",
    "End of dialog window.": "대화 상자 창 끝.",
    "{1} is loading.": "{1}이 (가)로드 중입니다."
});